# Generated by Django 4.1.7 on 2023-03-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_todo_list", "0002_alter_task_options_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="task", to="my_todo_list.tag"
            ),
        ),
    ]
