# Generated by Django 4.1.7 on 2023-03-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_todo_list", "0004_alter_tag_name_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                default=0, related_name="task", to="my_todo_list.tag"
            ),
        ),
    ]
